apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  creationTimestamp: null
  name: test-component3
  namespace: jvm-bld-test
spec:
  params:
  - name: git-revision
  resourcetemplates:
  - apiVersion: tekton.dev/v1beta1
    kind: PipelineRun
    metadata:
      annotations:
        appstudio.openshift.io/application: test-app
        appstudio.openshift.io/component: test-component3
        build.appstudio.openshift.io/build: "true"
        build.appstudio.openshift.io/type: build
        build.appstudio.openshift.io/version: "0.1"
        pipelines.appstudio.openshift.io/type: build
      creationTimestamp: null
      generateName: test-component3-
      labels:
        appstudio.openshift.io/application: test-app
        appstudio.openshift.io/component: test-component3
        build.appstudio.openshift.io/build: "true"
        build.appstudio.openshift.io/type: build
        build.appstudio.openshift.io/version: "0.1"
        pipelines.appstudio.openshift.io/type: build
      namespace: jvm-bld-test
    spec:
      params:
      - name: git-url
        value: https://github.com/stuartwdouglas/code-with-quarkus
      - name: output-image
        value: quay.io/redhat-appstudio/user-workload:jvm-bld-test-test-component3-$(tt.params.git-revision)
      pipelineRef:
        bundle: quay.io/redhat-appstudio/build-templates-bundle:748a03507b68aa610212e8031e3301ab943a14ef
        name: java-builder
      workspaces:
      - name: workspace
        volumeClaimTemplate:
          metadata:
            creationTimestamp: null
          spec:
            accessModes:
            - ReadWriteOnce
            resources:
              requests:
                storage: 1Gi
          status: {}
    status: {}
status: {}
