apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: test-component3
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: test-component3
    app.kubernetes.io/part-of: test-app
  name: test-component3
  namespace: jvm-bld-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: test-component3
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: test-component3
    spec:
      containers:
      - image: quay.io/redhat-appstudio/user-workload:jvm-bld-test-test-component3
        imagePullPolicy: Always
        name: container-image
        resources: {}
status: {}
